name: lokapos
description: "Lokapos Mobile App"
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_analytics: ^11.4.1
  carousel_slider: ^5.0.0
  get_it: ^8.0.3
  package_info_plus: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/